export const MOCK_INVENTORY = [
  {
    product_variant_id: 101,
    sku: "ADI-F50-41",
    name: "Tacos F50 Pro Firm",
    brand: "Adidas",
    category: "Tacos",
    gender: "Hombre",
    price: 1850.0,
    image: "/img/zapato1.jpg",
    quantity_on_hand: 12,
    reorder_level: 5,
  },
  {
    product_variant_id: 102,
    sku: "NIK-PEG42-42",
    name: "Nike Pegasus 42",
    brand: "Nike",
    category: "Calzado",
    gender: "Hombre",
    price: 1850.0,
    image: "/img/zapato2.jpg",
    quantity_on_hand: 4,
    reorder_level: 5, // Activa badge de Stock bajo (4 <= 5)
  },
  {
    product_variant_id: 103,
    sku: "ADI-UB-W38",
    name: "Ultraboost Light W",
    brand: "Adidas",
    category: "Calzado",
    gender: "Mujer",
    price: 1650.0,
    image: "/img/zapato1.jpg",
    quantity_on_hand: 2,
    reorder_level: 5,
  },
  {
    product_variant_id: 104,
    sku: "NIK-DFIT-M",
    name: "Playera Dri-FIT",
    brand: "Nike",
    category: "Ropa",
    gender: "Hombre",
    price: 180.0,
    image: "/img/playera1.jpg",
    quantity_on_hand: 0,
    reorder_level: 5, // Agotado
  },
];

export const MOCK_MOVEMENTS = [
  {
    id: 1,
    product_variant_id: 101,
    employee_id: 2,
    movement_type: "PURCHASE_IN",
    quantity: 15,
    reference: "INV-2026-001",
    notes: "Ingreso inicial de mercancía",
    createdAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: 2,
    product_variant_id: 101,
    employee_id: null,
    movement_type: "SALE_OUT",
    quantity: -3,
    reference: "checkout",
    notes: "Venta en tienda en línea",
    createdAt: "2026-09-02T14:30:00.000Z",
  },
  {
    id: 3,
    product_variant_id: 104,
    employee_id: 1,
    movement_type: "DAMAGE_OUT",
    quantity: -2,
    reference: "AJUSTE-MERMA",
    notes: "Empaque dañado durante traslado",
    createdAt: "2026-09-03T11:15:00.000Z",
  },
];